### ISSUE TITLE
problems in running the inference.py 

### ISSUE THREAD

**Issue by sarahrajabazdeh** [harsh2912/Background--removal#4]
Hi 
i hope you are fine. 
i am running the matting server on port 5000 and for the segmentation server the port is 3000.
here is the output of running inference.py and i print the response(405).
![inference](https://user-images.githubusercontent.com/33392969/126353569-125483ee-6e7f-43d1-ae38-69832f3d220b.png)

**Comment by harsh2912** [comment]
Is is working now?

**Comment by sarahrajabazdeh** [comment]
yes the problem is solved, thank you.
